---
name: Release to Ansible Galaxy

on:
  release:
    types: [created, edited, published, released]

jobs:
  release:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-galaxy-role-release.yaml@94f3b999608462ce6c0cfe1e4ea41606f75bc603 #feat/ansible-galaxy-role-release
    secrets: inherit
