---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '3 2 2 * *'

jobs:
  test:
    uses: adfinis/github-workflows-bareos/.github/workflows/molecule.yaml@v0.2.1
    with:
      systems: |
        {
          "config": [
            {
              "image": "debian",
              "tag": "latest"
            },
            {
              "image": "debian",
              "tag": "bullseye"
            },
            {
              "image": "enterpriselinux",
              "tag": "8"
            },
            {
              "image": "enterpriselinux",
              "tag": "latest"
            },
            {
              "image": "fedora",
              "tag": "39"
            },
            {
              "image": "opensuse",
              "tag": "latest"
            },
            {
              "image": "ubuntu",
              "tag": "latest"
            },
            {
              "image": "ubuntu",
              "tag": "focal"
            }
          ]
        }
